
export enum TemplateFieldType {
  SERVICE_TYPE = 'SERVICE_TYPE',
  MESSAGING_FREQUENCY = 'MESSAGING_FREQUENCY',
  DAY_OF_WEEK = 'DAY_OF_WEEK',
  START_OF_MESSAGES = 'START_OF_MESSAGES',
  END_OF_MESSAGES = 'END_OF_MESSAGES',
  CATEGORY_OF_MESSAGE = 'CATEGORY_OF_MESSAGE'
}
